name: Exploring Variables and secrets
on:
  push

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build
#       run: docker build -t docker.io/dockerUsername/imageName:latest

#     - name: Docker Login
#       run: docker login --username=yewaleajay --password=Luckey@123

  #   - name: docker publish
  #     run: docker push docker.io/yewaleajay/imageName:latest

  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - name: Docker Run
  #     run: docker run -d -p 8080:80 docker.io/dockerusername/imageName:latest

##################################   env at the step level##############
# jobs:
  # docker
  #     runs-on: ubuntu-latest
  #   steps:
  #   - name: Docker Build
  #     env:
  #       CONTAINER_REGISTRY: docker.io
  #       DOCKER_USERNAME: yewaleajay
  #       IMAGE_NAME: github-actions-nginx
  #     run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  #   - name: Docker Login
  #     env: 
  #       DOCKER_PASSWORD: Luckey@123
  #       DOCKER_USERNAME: yewaleajay
  #     run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

  #   - name: docker publish
  #       env:
  #         CONTAINER_REGISTRY: docker.io
  #         DOCKER_USERNAME: yewaleajay
  #         IMAGE_NAME: github-actions-nginx
  #       run: docker push docker.io/yewaleajay/imageName:latest

  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - name: Docker Run
  #     run: docker run -d -p 8080:80 docker.io/dockerusername/imageName:latest

##################################   env at the job level##############

# jobs:
#   docker:
#     env:
#       CONTAINER_REGISTRY: docker.io
#       DOCKER_USERNAME: yewaleajay
#       IMAGE_NAME: github-actions-nginx

#     steps:
#     - name: Docker Build
#       run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#     - name: Docker Login
#       run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#     - name: docker publish
#       run: docker push docker.io/yewaleajay/imageName:latest

#   deploy:
#     env:
#       IMAGE_NAME: github-actions-nginx
#       DOCKER_USERNAME: yewaleajay
#       CONTAINER_REGISTRY: docker.io      
#     needs: docker
#     runs-on: ubuntu-latest
#     steps: 
#     - name: Docker Run
#       run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


##############################env at Workflow level##############
env:
  IMAGE_NAME: github-actions-nginx
  DOCKER_USERNAME: yewaleajay
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx  

jobs:
  docker:
    steps:
    - name: Docker Build
      run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: docker publish
      run: docker push docker.io/yewaleajay/imageName:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
