name: Matrix config

on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
          os: ["windows-latest","ubuntu-latest","ubuntu-25.04"]
          image: ["nginx"]
          exclude: 
            - image: "nginx"
              os: windows-latest
          include: 
            - image: "busybox"
              os: ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
    - name: Echo Doker Details
      run: docker info
    
    - name: Run Images on ${{matrix.os}}
      run: docker run ${{matrix.image}}


      #   deploy-on-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Echo Docker Details
#         run: docker info
#       - name: Run Images
#         run: docker run hello-world



